version: '3.8'
services:
  db:
    image: postgres:16-bullseye@sha256:7174d2a352ad138906e3dc4a28a5d11b5a158180e9bff80beed8c8cc346f874c
    env_file:
      - ./.env.example
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-audit}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${SQL_PORT:-5432}:5432"  # Exponer correctamente
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $SQL_USER -d $SQL_DATABASE"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: on-failure

  web:
    build:
      context: ./
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/web_entrypoint.sh' ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Exponer correctamente
    depends_on:
      db:
        condition: service_healthy  # Esperar que PostgreSQL esté listo
    restart: on-failure

  nginx:
    image: nginx:stable-bullseye@sha256:ee187e563496b690edaab157f89db924cd35fab42631309f4d62957baecf7d6c
    ports:
      - "8888:80"  # Mapear correctamente al puerto 80
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      web:
        condition: service_started
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.13.0-management@sha256:ba406c7daaef53b59c92a13db37a27d0425579a40c59266d10022a40a8ba7242
    env_file:
      - ./.env.example
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: on-failure

  worker:
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/worker_entrypoint.sh' ]
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

volumes:
  db-data:
